name: release-please

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    if: ${{ !(contains(github.event.head_commit.message, 'chore')) }}
    uses: ./.github/workflows/run-unit-test.yml
  release-please:
    if: ${{ !(contains(github.event.head_commit.message, 'chore')) }}
    needs: [tests] # require tests to pass before release-please runs
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: vue3-lazy-hydration
